### ISSUE TITLE
[bug] sample_java is failing with mvn: command not found

### ISSUE THREAD

**Issue by manishas** [dry-dock/u14jav#5]
https://github.com/Shippable/pm/issues/4678

Here is the build link - 
https://app.shippable.com/builds/562eb64a41bf7f0d00e92cc6

Blog explaining how to install mvn 3.2.5 on ubuntu 14.04 - http://basicgroundwork.blogspot.com/2014/07/installing-maven-322-on-ubuntu-1404.html

**Comment by himanshu0503** [comment]
Closing this will be fixed as a part of https://github.com/dry-dock/u14jav/issues/9
